# Generated by Django 4.0.2 on 2022-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('lasty_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('hire_date', models.CharField(max_length=100)),
                ('job_id', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('manager_id', models.CharField(max_length=100)),
                ('department_id', models.CharField(max_length=100)),
            ],
        ),
    ]
