# Generated by Django 4.0.2 on 2022-02-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workers_image_workers_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='first_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='lasty_name',
            new_name='name',
        ),
    ]
