# Generated by Django 4.0.2 on 2022-02-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_remove_workers_manager_id_workers_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='manager',
        ),
    ]
