# Generated by Django 4.0.2 on 2022-02-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_workers_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workers.workers'),
        ),
    ]
